version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080